### PR TITLE
Fixed overhead attributes, fixed encore entries, added translations

### LINKED ISSUE #2: Missing localization for "useFlatpickrForDatepicker" and design decision
@AlexejKossmann 

Could you please add the missing localization for the field `tl_page.useFlatpickrForDatepicker`?

Thanks :-)

### LINKED ISSUE #3: Not working for filter element, issues in markup and encore
@AlexejKossmann 

1. I activated it in page and filter config element (which is type text), rebuilt encore and got

<input type="text" id="stat_items_startDate" name="stat_items[startDate]" required="required" aria-label="Von" flatpickr="Array" class="flatpickr-input form-control" data-flatpickr-active="1" data-input="1" prefix="flatpickr" data-flatpickr="{&quot;wrap&quot;:true,&quot;time_24hr&quot;:true,&quot;allowInput&quot;:true,&quot;dateFormat&quot;:&quot;d.m.Y&quot;,&quot;dateFormatIso8601&quot;:&quot;DD.MM.YYYY&quot;}">

There's an array in the input. Why a new attribute when the whole config is already in data-flatpickr?

2. In addition it's not working at all because the encore entries are not added (FrontendAsset::addFrontendAssets). Please dig into that as well.

3. the `unset_global_keys` entry in the encore config is wrong:

contao-flatpickr-bundle--library

it needs to be

contao-flatpickr-bundle-theme

because else the legacy css is added next to the encore css.

### PR DESCRIPTION
**Pull request by AlexejKossmann**
fixes #2  fixes #3

### CODE REVIEW

**Comment by AlexejKossmann** [comment]
i was not able to reproduce the #3 , but i experienced the frontend assets issues when i activated 'overrideFlatpickr' on a page and didnt activate flatpickr in the next step, but this is the expected bahavior

File: src/Manager/FlatpickrManager.php [hunk 1]
```diff
@@ -52,7 +52,12 @@ public function getOptionsFromDca(string $table, string $field): array
         $options = [];
         $dca = &$GLOBALS['TL_DCA'][$table];
 
-        if (isset($dca['fields'][$field]['eval']['flatpickr']) && \is_array($dca['fields'][$field]['eval']['flatpickr'])) {
+        if (
+            isset($dca['fields'][$field]['eval']['flatpickr'])
+            && \is_array($dca['fields'][$field]['eval']['flatpickr'])
+            && isset($dca['fields'][$field]['eval']['flatpickr']['options'])
+            && \is_array($dca['fields'][$field]['eval']['flatpickr']['options'])
+        ) {
```
Comment (Defcon0) [inline src/Manager/FlatpickrManager.php:60]: Redundant. You also can check nested array indices with isset, so

`isset($dca['fields'][$field]['eval']['flatpickr']['options']) && \is_array($dca['fields'][$field]['eval']['flatpickr']['options']`

is enough.

**Review by Defcon0 — CHANGES_REQUESTED** [review]
